version: "3"

services:
  order-dashboard-service:
    container_name: order-dashboard-dev-container
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - 8080:8080